export const CLOUDINARY_URL = 'https://res.cloudinary.com/ivanrice-c/image/upload/'
export const CLOUDINARY_LOW = 'c_scale,q_auto,w_450'
export const CLOUDINARY_HIGH = 'c_scale,q_auto,w_900'
export const FRONTEND = 'frontend'
export const TRESD = '3D'
